name: Playwright Tests
on:
  workflow_dispatch:
    inputs:
      browser:
        description: 'Select browser to test'
        required: true
        default: 'chromium'
        type: choice
        options:
          - chromium
          - firefox
          - webkit

  push:
    branches: [ main, master ]
    paths:
      - '**.js'
      - '**.ts'
      - 'package.json'
      - 'playwright.config.js'
      
  pull_request:
    branches: [ main, master ]
    paths:
      - '**.js'
      - '**.ts'
      - 'package.json'
      - 'playwright.config.js'

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        npm ci
        npx playwright install --with-deps
        
    - name: Run Playwright tests
      run: |
        npm run test
      env:
        CI: true
        
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report-${{ github.run_id }}
        path: playwright-report/
        retention-days: 30
